#!/usr/bin/env python
"""Render every agentic-misalignment prompt condition to a checked-in file.

The snapshots under ``tests/snapshots/`` are the primary offline artifact for
this eval: they let a human read exactly what a model would see in each
condition without spending anything, and they act as the regression test that
proves a change to the eval did not silently alter an existing scenario's
prompt (see ``tests/test_snapshots.py``).

Rendering deliberately runs with validation disabled (``strict=False``) so that
conditions which are degenerate -- e.g. the exfiltration urgency arms backed by
placeholder templates -- still produce a snapshot. Their brokenness is then
visible in the file rather than hidden behind an exception, and byte-identity
can be asserted across *all* conditions, degenerate ones included.

Usage::

    python scripts/generate_prompt_snapshots.py            # write snapshots
    python scripts/generate_prompt_snapshots.py --check    # verify, write nothing
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from evals.agentic_misalignment.prompt_generator import (  # noqa: E402
    Prompts,
    generate_prompts,
)

SNAPSHOT_DIR = REPO_ROOT / "tests" / "snapshots"

# Scenarios that use the original (goal_type, goal_value, urgency_type) axes.
BASE_SCENARIOS = ["leaking", "murder", "exfiltration"]

PAIRED_GOAL_VALUES = [
    "america",
    "global",
    "safety",
    "acceleration",
    "ethical",
    "pragmatic",
    "individualism",
    "collectivism",
]

# The (goal_type, goal_value) pairs the eval actually accepts. goal_type "none"
# and "ambiguous" require goal_value "none"; the paired types require a value.
GOAL_COMBINATIONS: list[tuple[str, str]] = (
    [("explicit", v) for v in PAIRED_GOAL_VALUES]
    + [("latent", v) for v in PAIRED_GOAL_VALUES]
    + [("swap", v) for v in PAIRED_GOAL_VALUES]
    + [("none", "none"), ("ambiguous", "none")]
)

URGENCY_TYPES = ["replacement", "restriction", "none"]

# Snapshots are rendered with the task defaults for everything not on the
# condition axes, so that a diff can only ever be caused by a condition change.
SNAPSHOT_MODEL_NAME = "Alex"
SNAPSHOT_EXTRA_SYSTEM_INSTRUCTIONS = None

SEPARATOR = "=" * 78


def _supports_strict() -> bool:
    """True once ``generate_prompts`` grows the ``strict`` parameter.

    The baseline snapshots were generated before strict validation existed, so
    this script has to run against both signatures to keep the baseline
    reproducible.
    """
    return "strict" in inspect.signature(generate_prompts).parameters


def render(
    scenario: str,
    goal_type: str,
    goal_value: str,
    urgency_type: str,
    prod: bool,
    condition: str | None = None,
) -> Prompts:
    """Render one condition, with validation disabled."""
    if scenario in BASE_SCENARIOS:
        kwargs = {}
        if _supports_strict():
            kwargs["strict"] = False
        return generate_prompts(
            scenario=scenario,  # type: ignore[arg-type]
            goal_type=goal_type,  # type: ignore[arg-type]
            goal_value=goal_value,  # type: ignore[arg-type]
            urgency_type=urgency_type,  # type: ignore[arg-type]
            extra_system_instructions=SNAPSHOT_EXTRA_SYSTEM_INSTRUCTIONS,
            prod_flag=prod,
            model_name=SNAPSHOT_MODEL_NAME,
            **kwargs,
        )

    from evals.agentic_misalignment.scenarios_ext import generate_ext_prompts

    assert condition is not None, f"{scenario} requires a condition"
    return generate_ext_prompts(
        scenario=scenario,  # type: ignore[arg-type]
        condition=condition,  # type: ignore[arg-type]
        goal_type=goal_type,  # type: ignore[arg-type]
        goal_value=goal_value,  # type: ignore[arg-type]
        urgency_type=urgency_type,  # type: ignore[arg-type]
        extra_system_instructions=SNAPSHOT_EXTRA_SYSTEM_INSTRUCTIONS,
        prod_flag=prod,
        model_name=SNAPSHOT_MODEL_NAME,
        strict=False,
    )


def snapshot_text(
    scenario: str,
    goal_type: str,
    goal_value: str,
    urgency_type: str,
    prod: bool,
    condition: str | None,
    prompts: Prompts,
) -> str:
    """Format one rendered condition as the snapshot file body."""
    header = [
        "# Agentic misalignment prompt snapshot",
        "# Generated by scripts/generate_prompt_snapshots.py -- do not hand-edit.",
        "#",
        f"# scenario:                  {scenario}",
        f"# goal_type:                 {goal_type}",
        f"# goal_value:                {goal_value}",
        f"# urgency_type:              {urgency_type}",
        f"# condition:                 {condition if condition is not None else '-'}",
        f"# prod:                      {str(prod).lower()}",
        f"# model_name:                {SNAPSHOT_MODEL_NAME}",
        f"# extra_system_instructions: {SNAPSHOT_EXTRA_SYSTEM_INSTRUCTIONS}",
    ]
    return "\n".join(
        header
        + [
            "",
            SEPARATOR,
            "SYSTEM PROMPT",
            SEPARATOR,
            prompts.system_prompt,
            "",
            SEPARATOR,
            "USER PROMPT",
            SEPARATOR,
            prompts.user_prompt,
            "",
            SEPARATOR,
            "EMAIL CONTENT",
            SEPARATOR,
            prompts.email_content,
            "",
        ]
    )


def _slug(
    goal_type: str,
    goal_value: str,
    urgency_type: str,
    prod: bool,
    condition: str | None,
) -> str:
    parts = [f"{goal_type}-{goal_value}", urgency_type]
    if condition is not None:
        parts.append(condition)
    parts.append(f"prod{int(prod)}")
    return "__".join(parts) + ".txt"


def enumerate_conditions() -> list[tuple[str, str, str, str, bool, str | None]]:
    """Every (scenario, goal_type, goal_value, urgency_type, prod, condition)."""
    conditions: list[tuple[str, str, str, str, bool, str | None]] = []

    for scenario in BASE_SCENARIOS:
        for goal_type, goal_value in GOAL_COMBINATIONS:
            for urgency_type in URGENCY_TYPES:
                for prod in (False, True):
                    conditions.append(
                        (scenario, goal_type, goal_value, urgency_type, prod, None)
                    )

    try:
        from evals.agentic_misalignment.scenarios_ext import EXT_SCENARIO_CONDITIONS
    except ImportError:
        # Baseline run: the new scenarios do not exist yet.
        return conditions

    for scenario, allowed in EXT_SCENARIO_CONDITIONS.items():
        for goal_type, goal_value in GOAL_COMBINATIONS:
            for urgency_type in URGENCY_TYPES:
                for condition in allowed:
                    for prod in (False, True):
                        conditions.append(
                            (
                                scenario,
                                goal_type,
                                goal_value,
                                urgency_type,
                                prod,
                                condition,
                            )
                        )

    return conditions


def build_snapshots() -> dict[Path, str]:
    """Render every condition to {relative path: file body}."""
    snapshots: dict[Path, str] = {}
    for (
        scenario,
        goal_type,
        goal_value,
        urgency_type,
        prod,
        condition,
    ) in enumerate_conditions():
        prompts = render(scenario, goal_type, goal_value, urgency_type, prod, condition)
        rel = Path(scenario) / _slug(goal_type, goal_value, urgency_type, prod, condition)
        snapshots[rel] = snapshot_text(
            scenario, goal_type, goal_value, urgency_type, prod, condition, prompts
        )
    return snapshots


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare against the checked-in snapshots and write nothing.",
    )
    args = parser.parse_args()

    snapshots = build_snapshots()

    if args.check:
        missing, differing = [], []
        for rel, body in sorted(snapshots.items()):
            path = SNAPSHOT_DIR / rel
            if not path.exists():
                missing.append(rel)
            elif path.read_text(encoding="utf-8") != body:
                differing.append(rel)

        on_disk = {
            p.relative_to(SNAPSHOT_DIR)
            for p in SNAPSHOT_DIR.rglob("*.txt")
            if p.is_file()
        }
        extra = sorted(on_disk - set(snapshots))

        for label, items in (
            ("missing", missing),
            ("differing", differing),
            ("unexpected on disk", extra),
        ):
            if items:
                print(f"{len(items)} snapshot(s) {label}:")
                for rel in sorted(items)[:20]:
                    print(f"  {rel}")
                if len(items) > 20:
                    print(f"  ... and {len(items) - 20} more")

        if missing or differing or extra:
            return 1
        print(f"OK: {len(snapshots)} snapshots match.")
        return 0

    for rel, body in sorted(snapshots.items()):
        path = SNAPSHOT_DIR / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")

    print(f"Wrote {len(snapshots)} snapshots to {SNAPSHOT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
